TELEGRAM_BOT_TOKEN = "8875001849:AAFHNjqvsXXvIupusMY4NYG41odPOhsvnsI"
TELEGRAM_CHAT_ID = "-1004486967940"
SUPABASE_URL = "https://cpdldgioucdqqfmrrkvr.supabase.co"
SUPABASE_KEY = "sb_publishable_snZrdJ0iPusF4M7aVBywqQ_0w3UV-oH"